# ==================================================
# Main 
# ==================================================
title: "NyX5yn3 // writeup_dump"
email: saulpabon57@gmail.com
description: "repositorio de writeups // cybersecurity // personal space" 
github_username: Nyx5yn3

# ==================================================
# (URLs)
# ==================================================
url: "https://Nyx5yn3.github.io" 
baseurl: "" 

# Style: saulpabon.github.io/dockerlabs/Example/
permalink: /:categories/:title/

# ==================================================
# Theme
# ==================================================
theme: jekyll-theme-hacker

# ==================================================
# Plugins 
# ==================================================
plugins:
  - jekyll-feed       
  - jekyll-seo-tag
  - jekyll-avatar    
